### ISSUE TITLE
Issue in swagger spec

### ISSUE THREAD

**Issue by hirenoble** [AdobeAtAdobe/kirby_docs#11]
In https://www.adobe.io/apis/experienceplatform/home/api-reference.html#!acpdr/swagger-specs/profile-segment-definitions-api.yaml 

/get/definitions parameter x-request-id states that it is a required parameter. Which is not true I was able to get a 200 OK response without providing x-request-id. Please verify and correct the same.

**Comment by dbenge** [comment]
i think the main repo for this content is internal.  this is a clone repo so people might not be looking out here on github at this issue.
